apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '3'
  creationTimestamp: '2020-06-29T15:45:10Z'
  generation: 3
  labels:
    app: web-rocket-server
  name: web-rocket-server
  namespace: default
  resourceVersion: '1360637'
  selfLink: /apis/apps/v1/namespaces/default/deployments/web-rocket-server
  uid: 66a983b0-779e-4bdf-88ee-b1acd415cdd2
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-rocket-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-rocket-server
    spec:
      containers:
        - image: winfordlin/webrocket:first
          imagePullPolicy: IfNotPresent
          name: webrocket
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-06-29T15:45:12Z'
      lastUpdateTime: '2020-06-29T15:45:12Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-06-29T15:45:10Z'
      lastUpdateTime: '2020-06-29T15:52:47Z'
      message: ReplicaSet "web-rocket-server-756b8db8c8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
